type: waymo
data_path_training: "data/waymo/training"
data_path_testing: "data/waymo/testing"
split: null
image_size: 384
frame_count: 2
preprocessed_path_training: "data/unimatch_flows/waymo/training"
preprocessed_path_testing: "data/unimatch_flows/waymo/testing"
return_depth: false
return_flow: true